### ISSUE TITLE
请问一下这两个代码在哪里啊？

### ISSUE THREAD

**Issue by lilepinghe** [FishAndWasabi/YOLO-MS#1]
from mmdet.utils import OptConfigType
from mmcv.cnn import ConvModule

**Comment by FishAndWasabi** [comment]
您好！这两个为[mmcv](https://github.com/open-mmlab/mmcv/tree/v2.0.0rc4)和[mmdetection](https://github.com/open-mmlab/mmdetection/tree/v3.0.0)官方库里的代码。您可以根据链接[mmcv.cnn.ConvModule](https://github.com/open-mmlab/mmcv/blob/v2.0.0rc4/mmcv/cnn/bricks/conv_module.py)和[mmdet.utils.OptConfigType](https://github.com/open-mmlab/mmdetection/blob/v3.0.0/mmdet/utils/typing_utils.py)查看具体的代码。

感谢您对我们工作的关注！

Best Wishes! 😊
