### ISSUE TITLE
TypeError: yolov5_collate() got an unexpected keyword argument '_scope_'

### ISSUE THREAD

**Issue by Bonasdljlkj** [FishAndWasabi/YOLO-MS#10]
你好，我在训练过程中遇到该报错，请问有解决办法嘛，谢谢。TypeError: yolov5_collate() got an unexpected keyword argument '_scope_'

**Comment by cxq521** [comment]
你的这个问题解决了吗？，如何解决的

**Comment by FishAndWasabi** [comment]
不好意思，没有及时回复您。该报错需要在config里的dataloader里做一些处理（我们已在commit [`5499293`](https://github.com/FishAndWasabi/YOLO-MS/commit/54992934d67590651a32274c64c5332b4c3eef24) 进行修复）:

```
train_dataloader = dict(
    ...
    collate_fn=dict(_delete_=True, type='yolov5_collate'),
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

val_dataloader = dict(
    ...
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

test_dataloader = val_dataloader
```

感谢您对我们工作的关注！

Best Wishes! 😊
