### ISSUE TITLE
如何将MSBlock加入到YOLO-X中呢

### ISSUE THREAD

**Issue by CcccccaptionOvO** [FishAndWasabi/YOLO-MS#12]
请问如何构造YOLO-X-MS网络结构

**Comment by FishAndWasabi** [comment]
实在不好意思。由于前段时间工作比较繁忙，没有及时回复该问题，还请谅解~

我们建议首先可以参考[YOLOv8MS](https://github.com/FishAndWasabi/YOLO-MS/blob/main/yoloms/models/backbones/yolov8ms.py)重构一下YOLOX的Backbone：[YOLOXCSPDarknet](https://github.com/open-mmlab/mmyolo/blob/main/mmyolo/models/backbones/csp_darknet.py)，并在重构的过程加入MS-Block和HKS protocol。接下来，可以参考[YOLOv8MS-PAFPN](https://github.com/FishAndWasabi/YOLO-MS/blob/main/yoloms/models/necks/yolov8ms_pafpn.py)重构一下YOLOX的Neck部分：[YOLOX_PAFPN](https://github.com/open-mmlab/mmyolo/blob/main/mmyolo/models/necks/yolox_pafpn.py)。其他的训练设置保持与YOLOX一样即可。

感谢您对我们工作的关注！

Best Wishes! 😊
