### ISSUE TITLE
训练自己的数据集，报错提示为TypeError: FormatCode() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by chihuajiao** [FishAndWasabi/YOLO-MS#14]
![image](https://github.com/FishAndWasabi/YOLO-MS/assets/79524642/801db06b-6c55-4ab3-bac2-41fb160cf947)

**Comment by gf-zhong** [comment]
1，解决了吗？

**Comment by chihuajiao** [comment]
这个问题解决，更新一下mmengine。但是改自己数据是真的麻烦，mmyolo得去改库文件

**Comment by FishAndWasabi** [comment]
实在不好意思。由于前段时间工作比较繁忙，没有及时回复该问题，还请谅解~

这个问题是由于安装了yapf v0.40.2最新版本而导致的。目前可以通过运行 `pip install yapf==0.40.1` 修复此错误。

感谢您对我们工作的关注！

Best Wishes! 😊

**Comment by FishAndWasabi** [comment]
感谢您提出关于数据使用的问题。

我们目前仅支持COCO格式的数据集，可以参考[issues4](https://github.com/FishAndWasabi/YOLO-MS/issues/4)。其他的数据集格式可以参考MMYOLO在YOLOMS中进行重构。我们会在之后添加新的数据集格式以方便各位进行开发。

Best Wishes! 😊

**Comment by chihuajiao** [comment]
谢谢您的细心回复，帮助我解决这个问题。我想用YOLO-MS作为我的基准网络，在我的数据集中进行训练。所以有一个小小请求想向作者咨询，mmyolo数据集重构的文章有索引和链接吗，如果能完成任务，一定会引用这篇优秀的工作。谢谢作者细心的解答！

Best Wishes! 😊

**Comment by FishAndWasabi** [comment]
如果您的数据集格式为COCO，可以直接参考[issues4](https://github.com/FishAndWasabi/YOLO-MS/issues/4)进行训练。如果您的数据集格式为非COCO格式（VOC， CrowdHuman等），您可以参考[mmyolo](https://github.com/open-mmlab/mmyolo/tree/main/mmyolo/datasets)和[mmdet](https://github.com/open-mmlab/mmdetection/tree/v3.1.0/mmdet/datasets)中的数据集类别进行重构。重构的位置可以设定在yoloms文件夹下，新建一个`yoloms/datasets/`的文件夹，在该文件夹中添加重构后的数据集类别。最后在_init_.py进行引用，然后在config处修改`dataset`字段，即可正常使用。

![image](https://github.com/FishAndWasabi/YOLO-MS/assets/45028025/57a7243d-bf05-409a-9e30-1b12d5eef21c)

![image](https://github.com/FishAndWasabi/YOLO-MS/assets/45028025/7c25f703-fe54-4b8c-86f1-467ff46d4d6b)


![image](https://github.com/FishAndWasabi/YOLO-MS/assets/45028025/6bd4af10-335e-4e8a-a7f1-a5c0b28d35bd)

希望能对您有帮助！

Best Wishes! 😊
