### ISSUE TITLE
请问如何训练自己的数据集

### ISSUE THREAD

**Issue by xywlpo** [FishAndWasabi/YOLO-MS#4]
请问如何训练自己的数据集，包括数据路径写在哪里？超参数应该如何调整

**Comment by FishAndWasabi** [comment]
1. 我们建议您先将数据集转换为COCO格式，下面是COCO目录结构的示例。其中，images文件夹存放图片文件，annotations文件夹存放标注文件（json格式）。标注文件可参考[COCO官方提供的格式](https://cocodataset.org/#format-data)进行构建。MMYOLO提供了一些现成数据集(balloon, labelme, yolo)的[转换脚本](https://mmyolo.readthedocs.io/zh_CN/latest/useful_tools/dataset_converters.html)，我们也将其移植到了[本仓库](https://github.com/FishAndWasabi/YOLO-MS/tree/main/tools/dataset_converters)中。

```
.
└── .${DATA_DIR}
    ├── images # image files
    │    ├── image1.jpg
    │    ├── image2.png
    │    └── ...
    ├── annotations # annotated files
          ├── train.json # labels of the training dataset
          └── test.json # labels of the test dataset
```

2. 可以使用下面的命令验证刚刚转换是否有问题：

```bash
python tools/analysis_tools/browse_coco_json.py --img-dir ${图片文件夹路径} \
                                                --ann-file ${COCO label json 路径}
```

3. 在config文件里对文件路径进行修改

```
train_dataloader = dict(dataset=dict(data_root="${DATA_DIR}",           # 训练集根目录
                                     ann_file="annotations/train.json", # 训练集annotation路径
                                     data_prefix=dict(img="images")))   # 训练集image路径
val_dataloader = dict(dataset=dict(data_root="${DATA_DIR}",             # 验证集根目录
                                   ann_file="annotations/test.json",    # 验证集annotation路径
                                   data_prefix=dict(img="images")))     # 验证集image路径
test_dataloader = val_dataloader
```

4. 建议可以尝试以默认的参数为基准对超参数进行调整。可以将我们提供的ckpt作为预训练模型，在新的数据集上进行finetune。RTMDet有类似的[例子](https://github.com/open-mmlab/mmyolo/blob/main/configs/rtmdet/rtmdet_tiny_fast_1xb12-40e_cat.py)，可以参考一下。


*我们的仓库基于MMYOLO构建，其他细节您可以参考他们官方文档提供的[教程](https://mmyolo.readthedocs.io/en/latest/recommended_topics/labeling_to_deployment_tutorials.html#prepare-custom-dataset)，里面有更详细的介绍。*

**Comment by xywlpo** [comment]
> 

感谢您的回复，我在训练自己的数据集时，出现下面的错误，请问是什么原因如何解决呢？
![image](https://github.com/FishAndWasabi/YOLO-MS/assets/728405/2ad52e1d-6021-405d-9a1d-87d26d5e5345)
![image](https://github.com/FishAndWasabi/YOLO-MS/assets/728405/bbc7ca0f-9fd3-4275-812c-eedb0ed94056)

**Comment by FishAndWasabi** [comment]
警告是正常的，不会影响训练程序。关于报错信息，我们建议您再检测一下config是否正确，data_loader.collate_fn可能存在不应该有的参数。

```python
train_dataloader = dict(
    ....    
   collate_fn=dict(type='yolov5_collate')
   ....
)
```

Best Wishes! 😊

**Comment by FishAndWasabi** [comment]
warning为正常现象，对训练程序没有影响。报错需要在config里的dataloader里做一些处理:

```
train_dataloader = dict(
    ...
    collate_fn=dict(_delete_=True, type='yolov5_collate'),
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

val_dataloader = dict(
    ...
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

test_dataloader = val_dataloader
```

Best Wishes! 😊
