### ISSUE TITLE
替换v6相关

### ISSUE THREAD

**Issue by yangyf123456** [FishAndWasabi/YOLO-MS#5]
您好，请问有尝试过替换v6更小尺寸，比如v6n结构吗？我看config里面是silu，不知道relu效果会掉多少？我复现v8的时候发现激活换成relu➕去掉dfl会掉2-3个点。

**Comment by FishAndWasabi** [comment]
1. 我们计划将我们的方法用于YOLOv6系列的其他模型中，完成后我们会尽快开源相关代码和模型文件。
2. 关于SiLU换成ReLU，我们认为该操作对模型性能的影响应该不大，我们在后续会补充相关实验以证明这一点。
3. YOLOv8-MS的训练配置与YOLOv8保持一致，我们仅改变了模型结构。我们认为掉点的原因可能主要在于去掉了Distribution Focal Loss。因为YOLOv8使用GFocal Loss[1]进行边界框回归，需要先将边界框表示为一组连续的概率分布（DFL），再通过积分转为常见的狄拉克分布的坐标表示（CIoU Loss）。两个阶段的边界框表示需要两个不同的回归损失。去掉了DFL，则会使通过概率分布表示边界框这一过程起不到作用，可能会对模型的训练过程产生不利影响。此外，由于更改了训练策略，可能还需要对训练超参进行适配，以达到最好的训练效果。

感谢您对我们工作的关注！

Best Wishes! 😊


[1] Li, et al. Generalized Focal Loss: Learning Qualified and Distributed Bounding Boxes for Dense Object Detection, NeurIPS2020

**Comment by yangyf123456** [comment]
感谢回复！
从
