### ISSUE TITLE
How to deploy yolo ms

### ISSUE THREAD

**Issue by tangent-T** [FishAndWasabi/YOLO-MS#6]
Hello, we would like to deploy YOLO MS. However, we have noticed that the public code is missing the docker/GPU/ directory and ${DEPLOY_CONFIG_FILE}. How can we resolve this issue?

**Comment by FishAndWasabi** [comment]
We have updated the ${DEPLOY_CONFIG_FILE} in the commit [`7d02597`](https://github.com/FishAndWasabi/YOLO-MS/commit/7d025974e049e9d8b4a2df02ed6002101dd49b9a). We recommend to use docker to deploy, the `docker/GPU/` directory is already in the docker images. You can refer to the office [docs](https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html) of mmdeploy's docker. Note that the `nvidia-docker` should be installed when using GPU. We hope this helps.

Thanks for your interest in our work!

Best Wishes! 😊

**Comment by FishAndWasabi** [comment]
We have updated the README, Dockerfile, and configs for deployment in the commit [`516cb88`](https://github.com/FishAndWasabi/YOLO-MS/commit/516cb88a9573f31e339f16177dd9733e9824ebaa) and commit [`9748224`](https://github.com/FishAndWasabi/YOLO-MS/commit/97482244bcb182d9b0240562ee268c0ae6ee5860), respectively. Note that we update `docker/GPU` to `docker/mmdepoly`. We are sorry for our mistakes and hope this helps.

Thanks for your interest in our work!

Best Wishes! 😊
