### ISSUE TITLE
请问怎么预测啊，将预测可视化

### ISSUE THREAD

**Issue by xiaofei624** [FishAndWasabi/YOLO-MS#7]

**Comment by FishAndWasabi** [comment]
我们提供了两种形式进行预测。第一种是单张图像的预测，您可以参考[Quick Demo](https://github.com/FishAndWasabi/YOLO-MS#-quick-demo-)。第二种是对整个数据集进行预测，您可以参考[Evaluation](https://github.com/FishAndWasabi/YOLO-MS#-training-and-evaluation-)。Evaluation代码可以通过设置`--show`或`--show-dir`来选择直接展示预测结果或将预测结果存储到指定位置。

感谢您对我们工作的关注！

Best Wishes! 😊
