### ISSUE TITLE
ms只下采样到16倍吗？

### ISSUE THREAD

**Issue by liiicon** [FishAndWasabi/YOLO-MS#9]

**Comment by FishAndWasabi** [comment]
不好意思，没有及时回复您。按照之前YOLO系列的设置，我们的结构是下采样到32倍，且这个设置并不是固定的。此外，论文中的图3存在问题（stage2，stage3和stage4分别为80×80，40×40，20×20），我们将尽快改正，并更新arxiv。

感谢您对我们工作的关注并指出我们的错误！

Best Wishes! 😊
